name: 기재부 접속 테스트
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 기재부 접속 테스트
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            curl -sk -o /dev/null -w "금감원: %{http_code}\n" "https://fss.or.kr/fss/bbs/B0000133/list.do?menuNo=200443"
            curl -sk -o /dev/null -w "회계기준원: %{http_code}\n" "https://www.kasb.or.kr/"
